### ISSUE TITLE
Empty line causes failure to read header

### ISSUE THREAD

**Issue by paulpdaniels** [rubenv/pofile#16]
The following example will not pick up the headers because of the empty line after the first comment:

```po

# placeholder_format_custom = \{\{.+?}}

#. extracted from code/
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-08-20 18:05-0700\n"
"PO-Revision-Date: 2015-08-20 18:06-0700\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.4\n"
"Last-Translator: \n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"Language: gi_US\n"

```

It is a simple fix to adjust it, but I am getting these files generated automatically, so I would prefer to not have to manually fix. I think these are valid files, but I am not familiar enough with .po files to say for sure.

**Comment by johnyb** [comment]
Indeed, this seems to be a bug :) msgcat command just removes the empty line, so I guess, we should do the same, here. Will add this example to the fixtures and make the tests green again.

**Comment by johnyb** [comment]
Thanks for spotting this, btw :) Added #17, to fix this issue.

**Comment by paulpdaniels** [comment]
Awesome! Thanks for the quick fix!
