### ISSUE TITLE
po.js errors out with latest version

### ISSUE THREAD

**Issue by jpzwarte** [rubenv/pofile#18]
/node_modules/gulp-angular-gettext/node_modules/angular-gettext-tools/node_modules/pofile/lib/po.js:69
    while (headers[headers.length - 1].indexOf('msgid ""') < 0) {
                                                           ^
TypeError: Cannot read property 'indexOf' of undefined

**Comment by johnyb** [comment]
That must have been me :\ I'll try to fix it ASAP

**Comment by johnyb** [comment]
@jpzwarte could you provide an example, when this happens? Is this an empty po file, or so?

**Comment by johnyb** [comment]
Ahh, no header at all, of course. That's a little tricky

**Comment by jpzwarte** [comment]
Yep, no header present.

**Comment by johnyb** [comment]
How did you manage to get your file parsed correctly, in this case? It should have been kind of broken, even before the last fix. It might have worked with a comment followed by a blank line, though. Or only a blank line. If the file started with the first msgid, this string should have been missing in the parsed result. Anyway, this should be resolved with PR #19

**Comment by jpzwarte** [comment]
Not sure, i haven't looked into it why exact the error occurred. Thanks for the fix!

**Comment by johnyb** [comment]
I added examples without headers in different variations. All are handled fine, now. Closing this issue, leaving it to PR #19.
