### ISSUE TITLE
Add support webpack for work in browser

### ISSUE THREAD

**Issue by iamruslanbakirov** [rubenv/pofile#33]
I have an issue 

ERROR in ./node_modules/pofile/lib/po.js
26 unchanged chunks
chunk {main} main.js, main.js.map (main) 2.91 MB [initial] [rendered]
Module not found: Error: Can't resolve 'fs' in '/Users/user/work/project/node_modules/pofile/lib'
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.2 MB [initial] [rendered]
｢wdm｣: Failed to compile.

maybe you can create split builds for nodejs and browser?

**Comment by JonathanBesson** [comment]
Hello,

Have you find a solution ?

**Comment by MiniGod** [comment]
There's a workaround you can do in your webpack config:

For `webpack@4`, set `node.fs = 'empty'`
For `webpack@5`, set `resolve.fallback.fs = false`

Although there's a workaround, I would personally like to see a separate browser build though. Without `PO.save()` and `PO.load()`.
