### ISSUE TITLE
Item typing not exported in TS declaration file

### ISSUE THREAD

**Issue by mrjpierce** [rubenv/pofile#35]
Currently running into this problem after last release:

```TypeScript
import PO, { Item } from 'pofile'; // Cannot export Item

private doSomething(str: string): PO.Item { // Error, cant use PO type as namespace to get item Type

	const item = new PO.Item(); // Works fine.
	item.msgid = str;
	return item;
}
```

Probably going to have the same issue with the Header type

**Comment by rubenv** [comment]
I'm no expert on TypeScript typings, so I can't really say for sure what the fix is.

@septs Can you have a look at this?

**Comment by septs** [comment]
@mrjpierce first, this package not is **esmodule**
The as designed, https://github.com/rubenv/pofile/blob/8bd781070346f88f7cef55d2f83662e76c7c1305/lib/po.js#L402
@rubenv the issue require use esmodule written this package

see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

**Comment by septs** [comment]
About get `PO.Item` instance type, please use the workaround code
```typescript
typeof PO["Item"]["prototype"]
```

**Comment by mrjpierce** [comment]
@septs 
```TypeScript
type Item = typeof PO["Item"]["prototype"];
```
This seems to work for now 👍. Xièxiè

**Comment by septs** [comment]
@rubenv The issue closable

**Comment by rubenv** [comment]
@septs thanks!

**Comment by septs** [comment]
@rubenv I want to rewrite this codebase using TypeScript.

**Comment by rubenv** [comment]
@septs Could you elaborate a bit on why and how you'd want to do this?

Keep in mind that this is a project I consider "finished": no big new functionality is needed (it does what it needs to do) and we can't break API / backwards compatibilty.

Rewrites are always risky. I'm all for strongly typing things, but it can only be done incrementally and in an extremely careful way: no user should ever see their code break.
