### ISSUE TITLE
`obsolete` is marked as private

### ISSUE THREAD

**Issue by remko** [rubenv/pofile#42]
The set of items returned from `parse` includes obsolete items. However, it seems you can't check for `obsolete`, as this field is marked `private` in the typescript definition. Is there a reason for this?

**Comment by rubenv** [comment]
I honestly have no idea (that part was contributed). If you think making it public is the correct thing: feel free to send a PR.

**Comment by Xenya0815** [comment]
I have also come across the same problem and would also like it to become `public`.

Currently I have to use `// @ts-expect-error` for checking if a translation is really required - and that feels hacky.

**Comment by rubenv** [comment]
Fixed in #44.
